# Generated by Django 5.0.3 on 2024-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('software_engineer', 'Software Engineer'), ('senior_software_engineer', 'Senior Software Engineer'), ('devops_engineer', 'DevOps Engineer'), ('qa_engineer', 'QA Engineer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('ui_ux_designer', 'UI/UX Designer'), ('graphic_designer', 'Graphic Designer'), ('system_architect', 'System Architect'), ('cto', 'Chief Technology Officer'), ('data_scientist', 'Data Scientist'), ('data_analyst', 'Data Analyst'), ('security_specialist', 'Security Specialist'), ('network_engineer', 'Network Engineer'), ('database_administrator', 'Database Administrator'), ('hr_manager', 'HR Manager'), ('sales_representative', 'Sales Representative'), ('customer_support', 'Customer Support')], default='software_engineer', max_length=50),
        ),
    ]
